--- !ruby/object:VR_ENV
width: 1105
height: 600
panel_pos: 360
run_command_line: ruby main.rb
open_files:
- "/home/eric/vrp/podcast/Untitled"
open_folders:
- "/home/eric/vrp/podcast"
current_file: "/home/eric/vrp/podcast/Untitled"
rdoc_command_line: rdoc -x README
vr_yaml_file: ".vr_settings.yaml"
notebook_panel_position: 400
current_line: 1
